---
title: "Poročilo pri predmetu Analiza podatkov s programom R"
author: "Študent FMF"
output:
  html_document: default
  pdf_document:
    includes:
      in_header: lib/styles.sty
    latex_engine: xelatex
runtime: shiny
---

```{r setup, echo=FALSE, results='hide', message=FALSE}
# Če želimo nastaviti pisave v PDF-ju, odkomentiramo
# in sledimo navodilom v programu.
#source("fontconfig.r", encoding = "UTF-8")

# Uvoz vseh potrebnih knjižnic
source("lib/libraries.r", encoding = "UTF-8")
```

# Izbira teme



Za temo sem si izbrala tenis. V projektu bom primerjala hitrost serve moških in žensk, najboljših 10 igralcev po številu zmag na Grand Slam turnirjih. Število zmag bom primerjala tudi po državah in tako videla, katera država je najuspešnejša. Primerjala bom tudi kako starost igralcev skozi čas in danes vpliva na njihovo kariero. 

#Obdelava, uvoz in čiščenje podatkov


Podatke sem uvozila v html oblikah iz [wikipedije](https://en.wikipedia.org/wiki/List_of_Grand_Slam_men%27s_singles_champions) in s [strani](http://www.ultimatetennisstatistics.com/seasons) s podtki o tenisu. Nato sem jih v uvozu preoblikovala v štiri tidy data tabele. 

###Opis tabel

V prvi tabeli **hitrosti.serve** so podatki o tenisačih, ki imajo najmočnejšo servo v zgodovini tenisa. Podatki so zbrani za prvih deset moških in žensk. Tabela vsebuje 5 stolpcev in sicer Razvrstitev (numeric), ki prikazuje prvih 10 mest, Igralec (character), ki pove ime igralca, Hitrost (value), meritev serve v km/s, Leto(integer), kdaj se je to zgodilo in Spol(factor).

```
kable(hitrosti.serve[1:5, ], caption ='Hitrost serve.')
```

V drugi tabeli **zmagovalci** so podatki o zmagovalcih Grand Slam turnirja in njihovem državljanstvu, razvrščene v 4 stolpce: Leto(integer), ki prikazuje leto prvenstva, Prvenstvo(character) predstavlja ime enega od štirih prvenstev Grand Slama (ZDA, Anglija, Francija ali Avstralija), stolpec Zmagovalec(character) prikazuje ime zmagovalca in stolpec Država(charachter) pove iz katere države prihaja.

V tretji tabeli **ponovitev** sta 2 stolpca, prvi stolpec Drzava(charachter) prikazuje države po vrstnem redu glede na število zmag na Grand Slam turnirjih. Drugi stolpec Ponovitve(numeric) pa ponazarja seštevek zmag iz tabele zmagovalci.

V četrti tabeli **tenisaci** so razporejeni najboljši igralci glede na sezono. Tabela ima 6 stolpcev, prvi Sezona(integer), drugi Na_prostem(integer) in tretji V_dvorani(integer), ki prikazujeta število dobljenih tekem na prostem in v dvorani. Četrti stolpec Prevladujoca_starost(integer), prikazuje starost, ki se je med igralci pojavila največkrat. Peti stolpec Igralec(character) pove ime igralca, šesti stolpec Drzava(character) pa prikazuje ime države, od kod igralec prihaja.
